config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :accounts do
    resources :envelopes
  end
  patch '/accounts/:id/deposit' => 'accounts#deposit', as: 'deposit'
  patch '/accounts/:id/withdrawal' => 'accounts#withdrawal', as: 'withdrawal'

  resources :home, only: [:index]
  root 'home#index', as: 'home'
  resources :users

end

app/models/account.rb
class Account < ActiveRecord::Base
  validates_presence_of :name
  belongs_to :user
  has_many :envelopes

  def make_deposit(amount)
    self.balance += amount
  end

  def make_withdrawal(amount)
    self.balance -= amount
  end
end

app/models/envelope.rb
class Envelope < ActiveRecord::Base
  validates_presence_of :name
  validates_numericality_of :budgeted_percentage
  validates_numericality_of :budgeted_amount
  validates_numericality_of :balance
  validate :amount_or_percentage
  validate :max, numericality: true, allow_nil: true
  before_save :balance_less_than_max
  belongs_to :account

  private

  def balance_less_than_max
    if self.max? && self.balance > self.max
      difference = self.balance - self.max
      self.balance -= difference
    end
  end

  def max_to_integer
    self.max.to_i
  end

  def max_amount
    self.max.to_f
  end

  def amount_or_percentage
    if checker.count != 1
      errors.add(:notice, "Please specify either amount or percentage but not both.")
    else
      return true
    end
  end

  def checker
    columns = [budgeted_amount, budgeted_percentage]
    columns.reduce([]) { |acc, column| acc << column if column > 0; acc }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :accounts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @account = Account.new
  end

  def index
    @accounts = current_user.accounts
  end

  def create
    account = current_user.accounts.create(account_params)
    if account.valid?
      redirect_to accounts_path
    end
  end

  def show
    @account = find_account(params[:id])
  end

  def edit
    @account = find_account(params[:id])
  end

  def update
    account = find_account(params[:id])
    account.assign_attributes(account_params)
    if account.save
      flash[:notice] = 'You have updated your Account'
      redirect_to accounts_path
    else
      flash[:notice] = 'Oops! Something went wrong and we were not able to save the updated information'
      redirect_to :back
    end
  end

  def deposit
    account = find_account(params[:id])
    account.make_deposit(balance_params)
    if account.save
      redirect_to account_path(account)
    else
      redirect_to :back
    end
  end

  def withdrawal
    account = find_account(params[:id])
    account.make_withdrawal(balance_params)
    if account.save
      redirect_to account_path(account)
    else
      redirect_to :back
    end
  end

  private

  def balance_params
    params[:account][:balance].to_d
  end

  def find_account(id)
    current_user.accounts.find(id)
  end

  def account_params
    params.require(:account).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/envelopes_controller.rb
class EnvelopesController < ApplicationController
  def new
    @account = Account.find(params[:account_id])
    @envelope = @account.envelopes.new
  end

  def create
    account = current_user.accounts.find(params[:account_id])
    @envelope = account.envelopes.create(envelope_params)
    if @envelope.save
      flash[:notice] = "Envelope Created"
      redirect_to account_path(account)
    else
      flash[:notice] = "Envelope was not Created"
      redirect_to new_account_envelope_path(account)
    end
  end

  def show
    account = current_user.accounts.find(params[:account_id])
    @envelope = account.envelopes.find(params[:id])
  end

  def edit
    @account = current_user.accounts.find(params[:account_id])
    @envelope = @account.envelopes.find(params[:id])
  end

  def update
    account = current_user.accounts.find(params[:account_id])
    @envelope = account.envelopes.find(params[:id])
    @envelope.assign_attributes(envelope_params)
    if @envelope.save
      flash[:notice] = "Envelope Updated"
      redirect_to account_envelope_path(account, @envelope)
    else
      flash[:notice] = "Envelope was not updated"
      redirect_to :back
    end
  end

  private

  def envelope_params
    params.require(:envelope).permit(:name, :budgeted_amount, :budgeted_percentage, :max)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/envelopes_helper.rb
module EnvelopesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/accounts/edit.html.erb
<%= form_for @account do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.submit 'Submit' %>
<% end %>

<%= link_to 'Create New Envelope', new_account_envelope_path(@account) %>

app/views/accounts/index.html.erb
<%= link_to "Sign Out", destroy_user_session_path(current_user), method: :delete %>
<%= link_to "Create New Account", new_account_path %>

<h2>My Accounts</h2>
<% unless @accounts.empty? %>
  <% @accounts.each do |account| %>
    <%= link_to account.name, account_path(account) %>
    <p>Account Balance</p>
    <%= number_to_currency(account.balance) %>
  <% end %>
<% end %>

app/views/accounts/new.html.erb
<%= form_for @account do |f| %>
<%= f.label "Name" %>
<%= f.text_field :name %>
<%= f.submit 'Submit' %>
<% end %>

app/views/accounts/show.html.erb
<h2><%= @account.name %></h2>

<p>
  <%= number_to_currency(@account.balance) %>
</p>

<% unless @account.envelopes.empty? %>
  <% @account.envelopes.each do |envelope| %>
    <h3>Envelope Name</h3>
    <%= link_to envelope.name, account_envelope_path(@account, envelope) %>
    <p>Envelope Balance</p>
    <%= number_to_currency(envelope.balance) %>
  <% end %>
<% end %>

<h2>Make Deposit</h2>
<%= form_for @account, url: deposit_path(@account) do |f| %>
  <%= f.label "Deposit Amount of"%>
  <%= f.text_field :balance, autofocus: true, value: 'Amount' %>
  <%= f.submit "into my #{@account.name} account"%>
<% end %>

<h2>Make Withdrawal</h2>
<%= form_for @account, url: withdrawal_path(@account) do |f| %>
  <%= f.label "Withdraw Amount of"%>
  <%= f.text_field :balance, autofocus: true, value: 'Amount' %>
  <%= f.submit "from my #{@account.name} account"%>
<% end %>

<%= link_to "Edit Account", edit_account_path(@account) %>

app/views/envelopes/edit.html.erb
<%= form_for [@account, @envelope] do |f| %>
<%= f.label 'Name' %>
<%= f.text_field :name %>
<%= f.label 'Amount' %>
<%= f.text_field :budgeted_amount %>
<%= f.label 'Percentage' %>
<%= f.text_field :budgeted_percentage %>
<%= f.label 'Max Amount if Desired' %>
<%= f.text_field :max %>
<%= f.submit 'Submit Changes' %>
<% end %>

app/views/envelopes/new.html.erb
<%= form_for [@account, @envelope] do |f| %>
<%= f.label 'Name' %>
<%= f.text_field :name %>
<%= f.label 'Amount' %>
<%= f.text_field :budgeted_amount %>
<%= f.label 'Percentage' %>
<%= f.text_field :budgeted_percentage %>
<%= f.label 'Max Amount if Desired' %>
<%= f.text_field :max %>
<%= f.submit 'Submit' %>
<% end %>

app/views/envelopes/show.html.erb
<h2><%= @envelope.name %></h2>

<% if @envelope.budgeted_percentage == 0.0 %>
  <h3>Budgeted Amount</h3>
  <%= number_to_currency(@envelope.budgeted_amount) %>
<% else %>
  <h3>Budgeted Percentage</h3>
  <%= number_to_percentage(@envelope.budgeted_percentage) %>
<% end %>
<h3>Balance</h3>
<%= number_to_currency(@envelope.balance) %>
<h3>Max Amount</h3>
<%= number_to_currency(@envelope.max) %>

<%= link_to "Edit Envelope", edit_account_envelope_path(@envelope.account, @envelope) %>

app/views/home/index.html.erb
<html>
  <head>
    <title>Welcome to BudgetMaster</title>
  </head>
  <body>
    <% if current_user %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Create Account', new_user_registration_path %>
      <%= link_to 'Sign In', user_session_path %>
    <% end %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Home', home_path %>
  <% if current_user && !current_page?(accounts_path) %>
    <%= link_to 'My Accounts', accounts_path %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/user/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.text_field :user_encrypted_password %>
<%= f.submit, 'Submit'%>
<% end %>

app/views/users/new.html.erb
<%= form_for (@user url: user_registration_path) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.text_field :encrypted_password %>
<%= f.submit 'Submit'%>
<% end %>